const mongoose = require('mongoose');

const ProductSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    price: {
        type: Number,
        required: true
    },
    // This is the image path generated by uploadProductImage route!
    image: {
        type: String,
        required: true
    }
});

module.exports = mongoose.model('Product', ProductSchema);